# Import Necessary Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from imblearn.combine import SMOTEENN

# Load the dataset

In [2]:
prabinAnuj = pd.read_csv("student_data.csv")
prabinAnuj.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [3]:
# data shape
prabinAnuj.shape

(395, 33)

In [4]:
# data length
len(prabinAnuj)

395

In [5]:
# data types
prabinAnuj.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [6]:
# data description
prabinAnuj.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [7]:
# data information
prabinAnuj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

# Checking Missing Values

In [8]:
# Checking missing values
print("\nMissing Values:")
print(prabinAnuj.isnull().sum())

Missing Values:
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

# Checking and Handling Zero Values in all (both numeric and non-numeric) columns

# Checking duplicate values per columns

In [9]:
df = prabinAnuj

In [10]:
categorical_col = df.select_dtypes(include=['object']).columns.tolist()
#list of columns that are numerical
numerical_col = df.select_dtypes(include=['number']).columns.tolist()
categorical_col

['school',
 'sex',
 'address',
 'famsize',
 'Pstatus',
 'Mjob',
 'Fjob',
 'reason',
 'guardian',
 'schoolsup',
 'famsup',
 'paid',
 'activities',
 'nursery',
 'higher',
 'internet',
 'romantic']

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score, mean_absolute_error
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,MinMaxScaler

In [12]:
new_df = pd.get_dummies(df, columns=['school','sex','address','famsize','Pstatus','Mjob','Fjob','reason','guardian','schoolsup','famsup','paid','activities','nursery','higher','internet',
 'romantic'])

In [13]:
new_df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,activities_no,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,True,False,False,True,False,True,True,False,True,False
1,17,1,1,1,2,0,5,3,3,1,...,True,False,True,False,False,True,False,True,True,False
2,15,1,1,1,2,3,4,3,2,2,...,True,False,False,True,False,True,False,True,True,False
3,15,4,2,1,3,0,3,2,2,1,...,False,True,False,True,False,True,False,True,False,True
4,16,3,3,1,2,0,4,3,2,1,...,True,False,False,True,False,True,True,False,True,False

In [14]:
X = new_df.drop('G3', axis=1).values
y = new_df['G3'].values

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((276, 58), (276,), (119, 58), (119,))

In [16]:
X_test

array([[17, 2, 1, ..., True, True, False],
       [18, 1, 2, ..., True, False, True],
       [18, 3, 3, ..., True, False, True],
       ...,
       [18, 3, 2, ..., True, True, False],
       [17, 2, 3, ..., False, True, False],
       [16, 4, 4, ..., True, False, True]], dtype=object)

In [17]:
# Scaling the data using pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('std_scalar', StandardScaler())
])

X_train = pipeline.fit_transform(X_train)
X_test = pipeline.transform(X_test)
X_test

array([[ 0.21668659, -0.69162477, -1.41883525, ...,  0.42959208,
         0.72447352, -0.72447352],
       [ 0.99338138, -1.62735241, -0.47975005, ...,  0.42959208,
        -1.3803127 ,  1.3803127 ],
       [ 0.99338138,  0.24410286,  0.45933515, ...,  0.42959208,
        -1.3803127 ,  1.3803127 ],
       ...,
       [ 0.99338138,  0.24410286, -0.47975005, ...,  0.42959208,
         0.72447352, -0.72447352],
       [ 0.21668659, -0.69162477,  0.45933515, ..., -2.32778965,
         0.72447352, -0.72447352],
       [-0.5600082 ,  1.1798305 ,  1.39842035, ...,  0.42959208,
        -1.3803127 ,  1.3803127 ]])

In [18]:
# initializing the algorithm
lin_reg = LinearRegression()

# Fitting Simple Linear Regression to the Training set
lin_reg.fit(X_train,y_train)

LinearRegression()

In [19]:
from sklearn import metrics
from sklearn.model_selection import cross_val_score

def cross_val(model):
    pred = cross_val_score(model, X, y, cv=10)
    return pred.mean()

def print_evaluate(true, predicted):  
    mae = metrics.mean_absolute_error(true, predicted)
    mse = metrics.mean_squared_error(true, predicted)
    rmse = np.sqrt(metrics.mean_squared_error(true, predicted))
    r2_square = metrics.r2_score(true, predicted)
    print('MAE:', mae)
    print('MSE:', mse)
    print('RMSE:', rmse)
    print('R2 Square', r2_square)
    print('__________________________________')
    
def evaluate(true, predicted):
    mae = metrics.mean_absolute_error(true, predicted)
    mse = metrics.mean_squared_error(true, predicted)
    rmse = np.sqrt(metrics.mean_squared_error(true, predicted))
    r2_square = metrics.r2_score(true, predicted)
    return mae, mse, rmse, r2_square

In [20]:
test_pred = lin_reg.predict(X_test)
train_pred = lin_reg.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

Test set evaluation:
_____________________________________
MAE: 1.535403381755989
MSE: 5.076676432939747
RMSE: 2.2531481160677713
R2 Square 0.7690536899371008
__________________________________
Train set evaluation:
_____________________________________
MAE: 1.1487388065707491
MSE: 2.734489628409065
RMSE: 1.6536292294251045
R2 Square 0.8664799575319733
__________________________________

In [21]:
results_df = pd.DataFrame(data=[["Linear Regression", *evaluate(y_test, test_pred) , cross_val(LinearRegression())]], 
                          columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', "Cross Validation"])
results_df

,Model,MAE,MSE,RMSE,R2 Square,Cross Validation
0,Linear Regression,1.535403,5.076676,2.253148,0.769054,0.78148

In [22]:
from sklearn.linear_model import RANSACRegressor

model = RANSACRegressor( max_trials=100)
model.fit(X_train, y_train)

test_pred = model.predict(X_test)
train_pred = model.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)
print('====================================')
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

Test set evaluation:
_____________________________________
MAE: 1.2954453132460368
MSE: 5.030115659377774
RMSE: 2.2427919340361857
R2 Square 0.77117181564195
__________________________________
====================================
Train set evaluation:
_____________________________________
MAE: 1.0676845625926383
MSE: 3.9849686236850004
RMSE: 1.996238618924351
R2 Square 0.8054213940545326
__________________________________

In [23]:
results_df_2 = pd.DataFrame(data=[["Robust Regression", *evaluate(y_test, test_pred) , cross_val(RANSACRegressor())]], 
                            columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', "Cross Validation"])
results_df = pd.merge(results_df , results_df_2 , how='outer')

In [24]:
results_df

,Model,MAE,MSE,RMSE,R2 Square,Cross Validation
0,Linear Regression,1.535403,5.076676,2.253148,0.769054,0.781480
1,Robust Regression,1.295445,5.030116,2.242792,0.771172,0.787546

In [25]:
from sklearn.tree import DecisionTreeRegressor

# Initializing the algorithm
dt_reg = DecisionTreeRegressor()

# Fitting Decision Tree Regressor to the Training set
dt_reg.fit(X_train, y_train)

# Predicting on the testing set
dt_test_pred = dt_reg.predict(X_test)
dt_train_pred = dt_reg.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, dt_test_pred)
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, dt_train_pred)

Test set evaluation:
_____________________________________
MAE: 1.361344537815126
MSE: 6.453781512605042
RMSE: 2.540429395319823
R2 Square 0.7064069286320064
__________________________________
Train set evaluation:
_____________________________________
MAE: 0.0
MSE: 0.0
RMSE: 0.0
R2 Square 1.0
__________________________________

In [27]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the model architecture
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(1)  # Output layer with one neuron for regression
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

# Evaluate the model
test_loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}')

# Predict on test set
y_pred = model.predict(X_test)

# You can also use the history object to plot training/validation loss over epochs

Epoch 1/100

C:\Users\acer\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - loss: 126.5353 - val_loss: 113.9696
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 109.5337 - val_loss: 96.1320
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 91.3726 - val_loss: 78.7518
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 77.3097 - val_loss: 61.4140
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 52.8028 - val_loss: 45.4010
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 39.4044 - val_loss: 31.9334
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.7847 - val_loss: 22.8327
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.1350 - val_loss: 18.0582
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.9837 - val_loss: 15.8609
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4264 - val_loss: 14.3780
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5837 - val_loss: 12.6556
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.6328 - val_loss: 11.4677
Epoch 13/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.1999 - val_loss: 10.5943
Epoch 14/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.0287 - val_loss: 9.9763
Epoch 15/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.5085 - val_loss: 9.4755
Epoch 16/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.0879 - val_loss: 9.0130
Epoch 17/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.4017 - val_loss: 8.6469
Epoch 18/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0241 - val_loss: 8.3951
Epoch 19/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.8662 - val_loss: 8.1299
Epoch 20/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.4418 - val_loss: 7.9653
Epoch 21/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.4698 - val_loss: 7.7550
Epoch 22/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.4246 - val_loss: 7.5935
Epoch 23/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1980 - val_loss: 7.4455
Epoch 24/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.6412 - val_loss: 7.3139
Epoch 25/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.6341 - val_loss: 7.1569
Epoch 26/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.8117 - val_loss: 7.0558
Epoch 27/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.1871 - val_loss: 6.9207
Epoch 28/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.5910 - val_loss: 6.8032
Epoch 29/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.2527 - val_loss: 6.6516
Epoch 30/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.9580 - val_loss: 6.5521
Epoch 31/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.9780 - val_loss: 6.4723
Epoch 32/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.6781 - val_loss: 6.4095
Epoch 33/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0873 - val_loss: 6.3160
Epoch 34/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.8298 - val_loss: 6.2400
Epoch 35/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4765 - val_loss: 6.1578
Epoch 36/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5240 - val_loss: 6.0879
Epoch 37/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.7217 - val_loss: 6.0442
Epoch 38/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2127 - val_loss: 6.0080
Epoch 39/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4986 - val_loss: 5.9161
Epoch 40/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1836 - val_loss: 5.9027
Epoch 41/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1731 - val_loss: 5.8530
Epoch 42/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0226 - val_loss: 5.8026
Epoch 43/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1568 - val_loss: 5.7562
Epoch 44/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9034 - val_loss: 5.7346
Epoch 45/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9099 - val_loss: 5.6825
Epoch 46/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7897 - val_loss: 5.6292
Epoch 47/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8240 - val_loss: 5.6071
Epoch 48/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8608 - val_loss: 5.6026
Epoch 49/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8425 - val_loss: 5.5680
Epoch 50/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6107 - val_loss: 5.5630
Epoch 51/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6466 - val_loss: 5.5474
Epoch 52/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6579 - val_loss: 5.5390
Epoch 53/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5008 - val_loss: 5.5261
Epoch 54/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.5753 - val_loss: 5.5169
Epoch 55/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5243 - val_loss: 5.5137
Epoch 56/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5302 - val_loss: 5.5091
Epoch 57/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4386 - val_loss: 5.5142
Epoch 58/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4865 - val_loss: 5.5100
Epoch 59/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5465 - val_loss: 5.5072
Epoch 60/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3409 - val_loss: 5.4991
Epoch 61/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3480 - val_loss: 5.5281
Epoch 62/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3352 - val_loss: 5.5366
Epoch 63/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2839 - val_loss: 5.5276
Epoch 64/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3249 - val_loss: 5.5423
Epoch 65/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3107 - val_loss: 5.5578
Epoch 66/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2136 - val_loss: 5.5541
Epoch 67/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2949 - val_loss: 5.5842
Epoch 68/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2107 - val_loss: 5.5924
Epoch 69/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1732 - val_loss: 5.5767
Epoch 70/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2186 - val_loss: 5.5779
Epoch 71/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1793 - val_loss: 5.5977
Epoch 72/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2179 - val_loss: 5.6114
Epoch 73/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.1463 - val_loss: 5.6317
Epoch 74/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1508 - val_loss: 5.6227
Epoch 75/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1659 - val_loss: 5.6397
Epoch 76/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1856 - val_loss: 5.6244
Epoch 77/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1746 - val_loss: 5.6322
Epoch 78/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1292 - val_loss: 5.6278
Epoch 79/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1232 - val_loss: 5.6383
Epoch 80/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1202 - val_loss: 5.6396
Epoch 81/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0869 - val_loss: 5.6266
Epoch 82/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0872 - val_loss: 5.6303
Epoch 83/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0894 - val_loss: 5.6509
Epoch 84/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0914 - val_loss: 5.6453
Epoch 85/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0817 - val_loss: 5.6317
Epoch 86/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0775 - val_loss: 5.6397
Epoch 87/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0824 - val_loss: 5.6475
Epoch 88/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0600 - val_loss: 5.6442
Epoch 89/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0596 - val_loss: 5.6302
Epoch 90/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0661 - val_loss: 5.6311
Epoch 91/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0702 - val_loss: 5.6390
Epoch 92/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0554 - val_loss: 5.6452
Epoch 93/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0520 - val_loss: 5.6296
Epoch 94/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0589 - val_loss: 5.6253
Epoch 95/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0482 - val_loss: 5.6150
Epoch 96/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0362 - val_loss: 5.6188
Epoch 97/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0294 - val_loss: 5.6203
Epoch 98/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0345 - val_loss: 5.6300
Epoch 99/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0423 - val_loss: 5.6262
Epoch 100/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0288 - val_loss: 5.6240
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.8492
Test Loss: 7.490950584411621
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Calculate evaluation metrics
mae_ann = mean_absolute_error(y_test, y_pred)
mse_ann = mean_squared_error(y_test, y_pred)
rmse_ann = np.sqrt(mse_ann)
r2_ann = r2_score(y_test, y_pred)

# Print evaluation metrics
print(f'Mean Absolute Error (MAE): {mae_ann}')
print(f'Mean Squared Error (MSE): {mse_ann}')
print(f'Root Mean Squared Error (RMSE): {rmse_ann}')
print(f'R-squared (R2) Score: {r2_ann}')

Mean Absolute Error (MAE): 1.9708006261777478
Mean Squared Error (MSE): 7.490950264994868
Root Mean Squared Error (RMSE): 2.7369600408107657
R-squared (R2) Score: 0.6592244265677047